apiVersion: v1
kind: Service
metadata:
  name: cymbal-frontend-service
spec:
  selector:
    app: cymbal-insurance-frontend
  type: LoadBalancer  # This will expose your service to the internet using a cloud provider's load balancer
  ports:
  - protocol: TCP
    port: 80  # The port the service is accessible on from the outside
    targetPort: 3000  # The container port to send requests to